version: '3.8'

services:
  app:
    image: app
    build: ./app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # depends_on:
    #   - db
    networks:
      my_network:
        ipv4_address: 172.20.0.3

  db:
    image: hospital
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      my_network:
        ipv4_address: 172.20.0.2

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
