FROM python:3.11-alpine

# Set the working directory in the container
WORKDIR /app

# Copies the code into /app
COPY . /app

# Installs the dependencies 
RUN pip install --no-cache-dir -r requirements.txt

# Runs main.py
#CMD ["python", "main.py"]
